openapi: 3.0.1
info:
  title: Task API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: "Server For Development And Docker"
  - url: https://tasksapiproject-js.herokuapp.com/api
    description: "Server For Production"
paths:
  /task/bulk:
    post:
      summary: Inserta 50 tareas aleatorias
      responses:
        201:
          description: All Task Created
          content: {}
        500:
          description: Internal Error
          content: {}
  /task:
    get:
      summary: Trae todas las tareas, filtradas por completadas o incompletas
      parameters:
        - name: status
          in: query
          required: true
          schema:
            type: boolean
      responses:
        200:
          description: All Task
          content: {}
        500:
          description: Internal Error
          content: {}
    post:
      summary: Agrega una nueva tarea
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                description:
                  type: string
                duration:
                  type: integer
                recordedTime:
                  type: integer
                status:
                  type: boolean
        required: false
      responses:
        201:
          description: Task Added
          content: {}
        400:
          description: Body cannot be empty
          content: {}
        500:
          description: Internal Error
          content: {}
      x-codegen-request-body-name: task
  /task/search:
    get:
      summary: Busca tareas por descripción
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: A successful response
          content: {}
        500:
          description: Internal Error
          content: {}
  /task/{id}:
    put:
      summary: Actualiza tarea por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                description:
                  type: string
                duration:
                  type: integer
                recordedTime:
                  type: integer
                status:
                  type: boolean
        required: false
      responses:
        200:
          description: A successful response
          content: {}
        400:
          description: Body cannot be empty
          content: {}
        404:
          description: Task Not Found
          content: {}
        500:
          description: Internal Error
          content: {}
      x-codegen-request-body-name: task
    delete:
      summary: Borrar tarea por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: A successful response
          content: {}
        404:
          description: Task Not Found
          content: {}
        500:
          description: Internal Error
          content: {}
components: {}

